### ISSUE TITLE
More informative error response 

### ISSUE THREAD

**Issue by bo55vxr** [smartsheet-platform/smartsheet-csharp-sdk#89]
I've started getting the error "**There was an issue connecting**" .. However, there is nothing to indicate the nature of the issue.

**Comment by brentaiipllc** [comment]
> I've started getting the error "**There was an issue connecting**" .. However, there is nothing to indicate the nature of the issue.

This is due to a TLS1.2 issue - not sure where the issue resides, but tested using a cURL call and was able to see that TLS1.2 - when not specifically called out - caused a failure of the call

**Comment by svidaurrazaga** [comment]
I'm getting theerror too. I was on an older version of the sdk and updated to the latest with RestSharp v106.2.2 and .NET 4.7.2. This issue is occurring on my web app but not a console app with the same version. Not sure yet on how to check it's the TLS issue on my end.

`
Smartsheet.Api.Internal.Http.HttpClientException
  HResult=0x80131500
  Message=There was an issue connecting.
  Source=smartsheet-csharp-sdk
  StackTrace:
   at Smartsheet.Api.Internal.Http.DefaultHttpClient.Request(HttpRequest smartsheetRequest)
   at Smartsheet.Api.Internal.AbstractResources.GetResource[T](String path, Type objectClass)
   at Smartsheet.Api.Internal.SheetResourcesImpl.GetSheet(Int64 sheetId, IEnumerable`1 includes, IEnumerable`1 excludes, IEnumerable`1 rowIds, IEnumerable`1 rowNumbers, IEnumerable`1 columnIds, Nullable`1 pageSize, Nullable`1 page, Nullable`1 ifVersionAfter)
   at Smartsheet.Api.Internal.SheetResourcesImpl.GetSheet(Int64 sheetId, IEnumerable`1 includes, IEnumerable`1 excludes, IEnumerable`1 rowIds, IEnumerable`1 rowNumbers, IEnumerable`1 columnIds, Nullable`1 pageSize, Nullable`1 page)
`

**Comment by bo55vxr** [comment]
I added the following to my app and it started working again .. 

            ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

It only from my Dev PC ... didn't seem to work when I deployed to PROD but I think that is more a case of network config with TLS1.2 in the internal LAN / Firewall / Proxy ... Yet to resolve that,

So, have Smartsheet now turned off anything below TLS1.2?

**Comment by brentaiipllc** [comment]
@bo55vxr - where did you add this?  Using my code, these lines didn't resolve the issue, but I may be too novice to understand.

            _**ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;**_
            long sheetid =longsheetid;
            singlesheet=_client.SheetResources.GetSheet(sheetid, null, null, null, null, null, null, null);

**Comment by bo55vxr** [comment]
@brentaiipllc First 2 lines of Main() on my Console app.

**Comment by brentaiipllc** [comment]
@bo55vxr - thanks - I got it by inserting that before creating the client.  It has to be they are shutting off of TLS1.0 and TLS1.1

**Comment by bo55vxr** [comment]
> @bo55vxr - thanks - I got it by inserting that before creating the client. It has to be they are shutting off of TLS1.0 and TLS1.1

TLS1.1 is still working. Their blog stated 1.0 was shut down in May but that may have been a passive shutdown and they finally hard-shut-off on Friday.

But if you need to make changes, then I guess pushing out to 1.2 is the obvious move.

**Comment by kfansler** [comment]
For the moment, Smartsheet has re-enabled TLS1.0 to give you all time to upgrade your configs. The plan of record is still to turn off support for 1.0 soon, but not today or tomorrow...

**Comment by timwellswa** [comment]
An opt-in to TLS 1.2 has been added to the SDK (2.5.0), so the client/caller configuration shouldn't be necessary.
